//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace teanicorns_art_trade_bot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("teanicorns_art_trade_bot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry &lt;@{0}&gt;. Entry week is currently taking place. Trade pairs are not formed until closed..
        /// </summary>
        internal static string REF_EW_TAKING_PLACE {
            get {
                return ResourceManager.GetString("REF_EW_TAKING_PLACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing art reference &lt;@{0}&gt;. Please provide an embeded image..
        /// </summary>
        internal static string REF_MISSING_ART {
            get {
                return ResourceManager.GetString("REF_MISSING_ART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry &lt;@{0}&gt;. Could not find an art trade partner for you..
        /// </summary>
        internal static string REF_MISSING_PARTNER {
            get {
                return ResourceManager.GetString("REF_MISSING_PARTNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry &lt;@{0}&gt;. There is no reference registered..
        /// </summary>
        internal static string REF_NOT_REG {
            get {
                return ResourceManager.GetString("REF_NOT_REG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;@{0}&gt; your reference has been removed..
        /// </summary>
        internal static string REF_REMOVED {
            get {
                return ResourceManager.GetString("REF_REMOVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello &lt;@{0}&gt;! Your hidden art trade partner was **{1}** and they are ready to show you their work!!.
        /// </summary>
        internal static string REF_REVEAL_FINAL {
            get {
                return ResourceManager.GetString("REF_REVEAL_FINAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry &lt;@{0}&gt;. Could not find your trade partner..
        /// </summary>
        internal static string REF_REVEAL_MISSING_PARTNER {
            get {
                return ResourceManager.GetString("REF_REVEAL_MISSING_PARTNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A notification was sent to your partner &lt;@{0}&gt;..
        /// </summary>
        internal static string REF_REVEAL_NOTIFY {
            get {
                return ResourceManager.GetString("REF_REVEAL_NOTIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry &lt;@{0}&gt;. But your partner did not receive the notification..
        /// </summary>
        internal static string REF_REVEAL_SORRY {
            get {
                return ResourceManager.GetString("REF_REVEAL_SORRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for the art reveal &lt;@{0}&gt;!.
        /// </summary>
        internal static string REF_REVEAL_THANKS {
            get {
                return ResourceManager.GetString("REF_REVEAL_THANKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing reference &lt;@{0}&gt;. Please provide a description and/or embeded image..
        /// </summary>
        internal static string REF_TRADE_MISSING_REF {
            get {
                return ResourceManager.GetString("REF_TRADE_MISSING_REF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your art trade partner is.. {1}, have fun &lt;@{0}&gt;!.
        /// </summary>
        internal static string REF_TRADE_PARTNER {
            get {
                return ResourceManager.GetString("REF_TRADE_PARTNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your entry has been registered successfully &lt;@{0}&gt;!.
        /// </summary>
        internal static string REF_TRADE_REG_SUCC {
            get {
                return ResourceManager.GetString("REF_TRADE_REG_SUCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry &lt;@{0}&gt;. Art trade is currently taking place. Can&apos;t modify existing entries.
        /// </summary>
        internal static string REF_TRADE_TAKING_PLACE {
            get {
                return ResourceManager.GetString("REF_TRADE_TAKING_PLACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme of this art trade is.. \&quot;{0}\&quot;.
        /// </summary>
        internal static string REF_TRADE_THEME {
            get {
                return ResourceManager.GetString("REF_TRADE_THEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;@{0}&gt; the trade start info has been set..
        /// </summary>
        internal static string TRADE_ACTIVE_SET {
            get {
                return ResourceManager.GetString("TRADE_ACTIVE_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry &lt;@{0}&gt;. You don&apos;t have required priviledges to run this command..
        /// </summary>
        internal static string TRADE_ADMIN_BLOCK {
            get {
                return ResourceManager.GetString("TRADE_ADMIN_BLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;@{0}&gt; the art trade month is already in progress..
        /// </summary>
        internal static string TRADE_ART_IN_PROGRESS {
            get {
                return ResourceManager.GetString("TRADE_ART_IN_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following users did not reveal their art, please do so once you are ready (you can reveal it even after the trade ended): {0}.
        /// </summary>
        internal static string TRADE_ART_LATE {
            get {
                return ResourceManager.GetString("TRADE_ART_LATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everyone submitted their art on time!.
        /// </summary>
        internal static string TRADE_ART_ON_TIME {
            get {
                return ResourceManager.GetString("TRADE_ART_ON_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending the full database &lt;@{0}&gt;..
        /// </summary>
        internal static string TRADE_BACKUP_DATABASE_DONE {
            get {
                return ResourceManager.GetString("TRADE_BACKUP_DATABASE_DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup file has been updated successfully &lt;@{0}&gt;..
        /// </summary>
        internal static string TRADE_BACKUP_DONE {
            get {
                return ResourceManager.GetString("TRADE_BACKUP_DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending the full history stream &lt;@{0}&gt;..
        /// </summary>
        internal static string TRADE_BACKUP_HISTORY_DONE {
            get {
                return ResourceManager.GetString("TRADE_BACKUP_HISTORY_DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;@{0}&gt; the art trade partner of {1} has been changed to {2}..
        /// </summary>
        internal static string TRADE_CHANGE_PAIR_DONE {
            get {
                return ResourceManager.GetString("TRADE_CHANGE_PAIR_DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry &lt;@{0}&gt;. Could not find the first partner..
        /// </summary>
        internal static string TRADE_CHANGE_PAIR_MISSING_FIRST {
            get {
                return ResourceManager.GetString("TRADE_CHANGE_PAIR_MISSING_FIRST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry &lt;@{0}&gt;. Could not find the second partner..
        /// </summary>
        internal static string TRADE_CHANGE_PAIR_MISSING_SECOND {
            get {
                return ResourceManager.GetString("TRADE_CHANGE_PAIR_MISSING_SECOND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry &lt;@{0}&gt;. Was not able to change your art trade partner..
        /// </summary>
        internal static string TRADE_CHANGE_PAIR_PROBLEM {
            get {
                return ResourceManager.GetString("TRADE_CHANGE_PAIR_PROBLEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry &lt;@{0}&gt;. Was not able to change the working channel. Current working channel is {1}..
        /// </summary>
        internal static string TRADE_CHANNEL_PROBLEM {
            get {
                return ResourceManager.GetString("TRADE_CHANNEL_PROBLEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel has been set successfully &lt;@{0}&gt;..
        /// </summary>
        internal static string TRADE_CHANNEL_SET {
            get {
                return ResourceManager.GetString("TRADE_CHANNEL_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The art trade ends on.. {0}..
        /// </summary>
        internal static string TRADE_ENDS_ON {
            get {
                return ResourceManager.GetString("TRADE_ENDS_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All entries successfully removed &lt;@{0}&gt;. Backup file updated..
        /// </summary>
        internal static string TRADE_ENTRIES_CLEARED {
            get {
                return ResourceManager.GetString("TRADE_ENTRIES_CLEARED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entries have been shuffled successfully &lt;@{0}&gt;..
        /// </summary>
        internal static string TRADE_ENTRIES_SHUFFLE {
            get {
                return ResourceManager.GetString("TRADE_ENTRIES_SHUFFLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;@{0}&gt; the entry week is already in progress..
        /// </summary>
        internal static string TRADE_EW_IN_PROGRESS {
            get {
                return ResourceManager.GetString("TRADE_EW_IN_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing all entries &lt;@{0}&gt;. Each next entry is the partner of the previous one..
        /// </summary>
        internal static string TRADE_LISTING_ALL {
            get {
                return ResourceManager.GetString("TRADE_LISTING_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @everyone the **entry week** started. **We are accepting new entries!**.
        /// </summary>
        internal static string TRADE_NEW_ENTRIES {
            get {
                return ResourceManager.GetString("TRADE_NEW_ENTRIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @everyone the art **trade month** started. **We are no longer accepting new entries!**.
        /// </summary>
        internal static string TRADE_NO_NEW_ENTRIES {
            get {
                return ResourceManager.GetString("TRADE_NO_NEW_ENTRIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database has been loaded successfully &lt;@{0}&gt;..
        /// </summary>
        internal static string TRADE_RESTORE_DATABASE_DONE {
            get {
                return ResourceManager.GetString("TRADE_RESTORE_DATABASE_DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry &lt;@{0}&gt;. There have been some problems when loading the database..
        /// </summary>
        internal static string TRADE_RESTORE_DATABASE_PROBLEM {
            get {
                return ResourceManager.GetString("TRADE_RESTORE_DATABASE_PROBLEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All entries successfully restored &lt;@{0}&gt;..
        /// </summary>
        internal static string TRADE_RESTORE_DONE {
            get {
                return ResourceManager.GetString("TRADE_RESTORE_DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The history has been loaded successfully &lt;@{0}&gt;..
        /// </summary>
        internal static string TRADE_RESTORE_HISTORY_DONE {
            get {
                return ResourceManager.GetString("TRADE_RESTORE_HISTORY_DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry &lt;@{0}&gt;. There have been some problems when loading the history..
        /// </summary>
        internal static string TRADE_RESTORE_HISTORY_PROBLEM {
            get {
                return ResourceManager.GetString("TRADE_RESTORE_HISTORY_PROBLEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry &lt;@{0}&gt;. No backup file found..
        /// </summary>
        internal static string TRADE_RESTORE_NO_BACKUP {
            get {
                return ResourceManager.GetString("TRADE_RESTORE_NO_BACKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find any entry info for:.
        /// </summary>
        internal static string TRADE_SEND_ENTRIES_MISSING {
            get {
                return ResourceManager.GetString("TRADE_SEND_ENTRIES_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All trade participants received their partners..
        /// </summary>
        internal static string TRADE_SEND_PARTNERS_DONE {
            get {
                return ResourceManager.GetString("TRADE_SEND_PARTNERS_DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find an art trade partner for:.
        /// </summary>
        internal static string TRADE_SEND_PARTNERS_MISSING {
            get {
                return ResourceManager.GetString("TRADE_SEND_PARTNERS_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users not found:.
        /// </summary>
        internal static string TRADE_SEND_USERS_MISSING {
            get {
                return ResourceManager.GetString("TRADE_SEND_USERS_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently taking place.. **Entry week**..
        /// </summary>
        internal static string TRADE_TAKING_PLACE_EW {
            get {
                return ResourceManager.GetString("TRADE_TAKING_PLACE_EW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently taking place.. **Trade month**..
        /// </summary>
        internal static string TRADE_TAKING_PLACE_TM {
            get {
                return ResourceManager.GetString("TRADE_TAKING_PLACE_TM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry &lt;@{0}&gt;. The provided theme is null or whitespace..
        /// </summary>
        internal static string TRADE_THEME_NULL {
            get {
                return ResourceManager.GetString("TRADE_THEME_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry &lt;@{0}&gt;. There has been a problem when setting the theme..
        /// </summary>
        internal static string TRADE_THEME_PROBLEM {
            get {
                return ResourceManager.GetString("TRADE_THEME_PROBLEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The theme has been set successfully &lt;@{0}&gt;!.
        /// </summary>
        internal static string TRADE_THEME_SET {
            get {
                return ResourceManager.GetString("TRADE_THEME_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme of this month&apos;s art trade is.. \&quot;{0}\&quot;..
        /// </summary>
        internal static string TRADE_THIS_THEME {
            get {
                return ResourceManager.GetString("TRADE_THIS_THEME", resourceCulture);
            }
        }
    }
}
