//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace teanicorns_art_trade_bot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("teanicorns_art_trade_bot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;@{0}&gt; there already is a {1} with this name registered.
        /// </summary>
        internal static string GLOBAL_DUPLICAT_ARG {
            get {
                return ResourceManager.GetString("GLOBAL_DUPLICAT_ARG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;@{0}&gt; {1} is already in progress..
        /// </summary>
        internal static string GLOBAL_IN_PROGRESS {
            get {
                return ResourceManager.GetString("GLOBAL_IN_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;@{0}&gt; your request has been completed.
        /// </summary>
        internal static string GLOBAL_REQUEST_DONE {
            get {
                return ResourceManager.GetString("GLOBAL_REQUEST_DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;@{0}&gt; your request has failed.
        /// </summary>
        internal static string GLOBAL_REQUEST_FAIL {
            get {
                return ResourceManager.GetString("GLOBAL_REQUEST_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry &lt;@{0}&gt;. Unknown or missing input argument..
        /// </summary>
        internal static string GLOBAL_UNKNOW_ARG {
            get {
                return ResourceManager.GetString("GLOBAL_UNKNOW_ARG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @everyone the **trade** is ending, please send me your wonderful art using the \&quot;{0}ra\&quot; or \&quot;{1}reveal art\&quot; command..
        /// </summary>
        internal static string GOOGLE_TRADE_ENDING_NOW {
            get {
                return ResourceManager.GetString("GOOGLE_TRADE_ENDING_NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @everyone the art **Trade month** will be ending in 7 days, please reveal your art submissions until then..
        /// </summary>
        internal static string GOOGLE_TRADE_ENDING_SOON1 {
            get {
                return ResourceManager.GetString("GOOGLE_TRADE_ENDING_SOON1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @everyone the art **Trade month** will be ending in 3 days, please reveal your art submissions until then..
        /// </summary>
        internal static string GOOGLE_TRADE_ENDING_SOON2 {
            get {
                return ResourceManager.GetString("GOOGLE_TRADE_ENDING_SOON2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @everyone the art **Trade month** will be ending in 1 day, please reveal your art submissions until then..
        /// </summary>
        internal static string GOOGLE_TRADE_ENDING_SOON3 {
            get {
                return ResourceManager.GetString("GOOGLE_TRADE_ENDING_SOON3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Admin commands**.
        /// </summary>
        internal static string INFO_ADMIN_CMD_LIST {
            get {
                return ResourceManager.GetString("INFO_ADMIN_CMD_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Commands**.
        /// </summary>
        internal static string INFO_CMD_LIST {
            get {
                return ResourceManager.GetString("INFO_CMD_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello &lt;@{0}&gt;, I am art-trade-bot, written in Discord.Net ({1}).
        ///For more information about a specific command please type {2}{3} followed by the command name at the end.
        ///For example `{2}{3} {4}`.
        /// </summary>
        internal static string INFO_INTRO {
            get {
                return ResourceManager.GetString("INFO_INTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Parameters**.
        /// </summary>
        internal static string INFO_PARAM_CMD_LIST {
            get {
                return ResourceManager.GetString("INFO_PARAM_CMD_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry &lt;@{0}&gt;. {1} Please try \&quot;{2}about\&quot; for more info..
        /// </summary>
        internal static string MAIN_PROGRAM_MESSAGE_RECEIVED {
            get {
                return ResourceManager.GetString("MAIN_PROGRAM_MESSAGE_RECEIVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry &lt;@{0}&gt;. Entry week is currently taking place. Trade pairs are not formed until closed..
        /// </summary>
        internal static string REF_EW_TAKING_PLACE {
            get {
                return ResourceManager.GetString("REF_EW_TAKING_PLACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing art reference &lt;@{0}&gt;. Please provide an embeded image..
        /// </summary>
        internal static string REF_MISSING_ART {
            get {
                return ResourceManager.GetString("REF_MISSING_ART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry &lt;@{0}&gt;. Could not find an art trade partner for you..
        /// </summary>
        internal static string REF_MISSING_PARTNER {
            get {
                return ResourceManager.GetString("REF_MISSING_PARTNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry &lt;@{0}&gt;. There is no reference registered..
        /// </summary>
        internal static string REF_NOT_REG {
            get {
                return ResourceManager.GetString("REF_NOT_REG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello &lt;@{0}&gt;! Your hidden art trade partner was **{1}** and they are ready to show you their work!!.
        /// </summary>
        internal static string REF_REVEAL_FINAL {
            get {
                return ResourceManager.GetString("REF_REVEAL_FINAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for the reveal &lt;@{0}&gt; A notification was sent to your partner &lt;@{1}&gt;..
        /// </summary>
        internal static string REF_REVEAL_NOTIFY {
            get {
                return ResourceManager.GetString("REF_REVEAL_NOTIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry &lt;@{0}&gt;. But your partner did not receive the notification..
        /// </summary>
        internal static string REF_REVEAL_SORRY {
            get {
                return ResourceManager.GetString("REF_REVEAL_SORRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry &lt;@{0}&gt; but you did not commit the art for the last trade, you cannot enter the current trade..
        /// </summary>
        internal static string REF_TRADE_LAST_MONTH_ART_MISSING {
            get {
                return ResourceManager.GetString("REF_TRADE_LAST_MONTH_ART_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing reference &lt;@{0}&gt;. Please provide a description and/or embeded image..
        /// </summary>
        internal static string REF_TRADE_MISSING_REF {
            get {
                return ResourceManager.GetString("REF_TRADE_MISSING_REF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your art trade partner is.. {1}, have fun &lt;@{0}&gt;!.
        /// </summary>
        internal static string REF_TRADE_PARTNER {
            get {
                return ResourceManager.GetString("REF_TRADE_PARTNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your entry has been registered successfully &lt;@{0}&gt;!.
        /// </summary>
        internal static string REF_TRADE_REG_SUCC {
            get {
                return ResourceManager.GetString("REF_TRADE_REG_SUCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry &lt;@{0}&gt;. please register to the art trade first..
        /// </summary>
        internal static string REF_TRADE_REGISTER_FIRST {
            get {
                return ResourceManager.GetString("REF_TRADE_REGISTER_FIRST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry &lt;@{0}&gt;. Art trade is currently taking place. Can&apos;t modify existing entries.
        /// </summary>
        internal static string REF_TRADE_TAKING_PLACE {
            get {
                return ResourceManager.GetString("REF_TRADE_TAKING_PLACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;@{0}&gt; here is a list of your registered themes:.
        /// </summary>
        internal static string REF_TRADE_THEME_POOL {
            get {
                return ResourceManager.GetString("REF_TRADE_THEME_POOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry &lt;@{0}&gt;. You don&apos;t have required priviledges to run this command..
        /// </summary>
        internal static string TRADE_ADMIN_BLOCK {
            get {
                return ResourceManager.GetString("TRADE_ADMIN_BLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following users did not reveal their art, please do so once you are ready (you can reveal it even after the trade ended): {0}.
        /// </summary>
        internal static string TRADE_ART_LATE {
            get {
                return ResourceManager.GetString("TRADE_ART_LATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following users did not reveal their art for the previous trade (themed {0}): {1}.
        /// </summary>
        internal static string TRADE_ART_LATE_1 {
            get {
                return ResourceManager.GetString("TRADE_ART_LATE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following users did not reveal their art for the previous trade (themed {0}): {1}.
        /// </summary>
        internal static string TRADE_ART_LATE_2 {
            get {
                return ResourceManager.GetString("TRADE_ART_LATE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello &lt;@{0}&gt;the current trade ({1} themed) is ending but you did not reveal your art in time, please do so as soon as you have the time, thanks!.
        /// </summary>
        internal static string TRADE_ART_LATE_DM {
            get {
                return ResourceManager.GetString("TRADE_ART_LATE_DM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everyone submitted their art on time!.
        /// </summary>
        internal static string TRADE_ART_ON_TIME {
            get {
                return ResourceManager.GetString("TRADE_ART_ON_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending the full history stream &lt;@{0}&gt;..
        /// </summary>
        internal static string TRADE_BACKUP_HISTORY_DONE {
            get {
                return ResourceManager.GetString("TRADE_BACKUP_HISTORY_DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The art trade ends on.. {0}..
        /// </summary>
        internal static string TRADE_ENDS_ON {
            get {
                return ResourceManager.GetString("TRADE_ENDS_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entries have been shuffled successfully &lt;@{0}&gt;..
        /// </summary>
        internal static string TRADE_ENTRIES_SHUFFLE {
            get {
                return ResourceManager.GetString("TRADE_ENTRIES_SHUFFLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing all entries. Each next entry is the partner of the previous one..
        /// </summary>
        internal static string TRADE_LIST_ENTRIES {
            get {
                return ResourceManager.GetString("TRADE_LIST_ENTRIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `{0}` is currently active.
        /// </summary>
        internal static string TRADE_LIST_ONOFF {
            get {
                return ResourceManager.GetString("TRADE_LIST_ONOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing other info.. working channel is.. \&quot;{0}\&quot;, trade is taking place from.. {1} to {2} ({3} days), notify flags.. {4}, trade end forced.. {5}.
        /// </summary>
        internal static string TRADE_LIST_SETTINGS {
            get {
                return ResourceManager.GetString("TRADE_LIST_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the **entry week** started. **We are accepting new entries!**
        ///please use `{0}{1}`  to register or use `{0}{2}` if you need more info.
        /// </summary>
        internal static string TRADE_NEW_ENTRIES {
            get {
                return ResourceManager.GetString("TRADE_NEW_ENTRIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @everyone the art **trade month** started. **We are no longer accepting new entries!**
        ///please use `{0}{1}` to show your finished art piece or use `{0}{2}` if you need more info
        ///but please wait until the end of the trade when everybody has fihisned their art too.
        /// </summary>
        internal static string TRADE_NO_NEW_ENTRIES {
            get {
                return ResourceManager.GetString("TRADE_NO_NEW_ENTRIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please choose which theme you&apos;d like for this month&apos;s art trade 
        ///the poll will take `{0}` days and theme with the most votes wins! (^•^).
        /// </summary>
        internal static string TRADE_THEME_POOL_START {
            get {
                return ResourceManager.GetString("TRADE_THEME_POOL_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `{0}` is currently taking place in `{1}` channel (^•^).
        /// </summary>
        internal static string TRADE_THEME_POOL_SUBS {
            get {
                return ResourceManager.GetString("TRADE_THEME_POOL_SUBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme of this month&apos;s art trade is.. \&quot;{0}\&quot;..
        /// </summary>
        internal static string TRADE_THIS_THEME {
            get {
                return ResourceManager.GetString("TRADE_THIS_THEME", resourceCulture);
            }
        }
    }
}
