//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace teanicorns_art_trade_bot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("teanicorns_art_trade_bot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the **entry week** started. **We are accepting new entries!**
        ///please use `{0}{1}`  to register or use `{0}{2}` if you need more info.
        /// </summary>
        internal static string ENTRY_WEEK {
            get {
                return ResourceManager.GetString("ENTRY_WEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you can use `{0}{1}` to {2}.
        /// </summary>
        internal static string GLOBAL_CMDHELP {
            get {
                return ResourceManager.GetString("GLOBAL_CMDHELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;@{0}&gt; there already is a {1} with this name registered.
        /// </summary>
        internal static string GLOBAL_DUPLICAT_ARG {
            get {
                return ResourceManager.GetString("GLOBAL_DUPLICAT_ARG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to there are no {0} registered at the moment.
        /// </summary>
        internal static string GLOBAL_EMPTY {
            get {
                return ResourceManager.GetString("GLOBAL_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry &lt;@{0}&gt;. Error: {1}.
        /// </summary>
        internal static string GLOBAL_ERROR {
            get {
                return ResourceManager.GetString("GLOBAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;@{0}&gt; {1} is already in progress..
        /// </summary>
        internal static string GLOBAL_IN_PROGRESS {
            get {
                return ResourceManager.GetString("GLOBAL_IN_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;@{0}&gt; I couldn&apos;t find your {1}.
        /// </summary>
        internal static string GLOBAL_ITEM_NOT_FOUND {
            get {
                return ResourceManager.GetString("GLOBAL_ITEM_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;@{0}&gt; max number of {1} reached.
        /// </summary>
        internal static string GLOBAL_MAX_NUM_OF_ARGS {
            get {
                return ResourceManager.GetString("GLOBAL_MAX_NUM_OF_ARGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;@{0}&gt; I need {1}, please send me again.
        /// </summary>
        internal static string GLOBAL_MISSING_INPUT {
            get {
                return ResourceManager.GetString("GLOBAL_MISSING_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;@{0}&gt; your request has been completed. {1}.
        /// </summary>
        internal static string GLOBAL_SUCCESS {
            get {
                return ResourceManager.GetString("GLOBAL_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry &lt;@{0}&gt;. Unknown or missing input argument..
        /// </summary>
        internal static string GLOBAL_UNKNOW_ARG {
            get {
                return ResourceManager.GetString("GLOBAL_UNKNOW_ARG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @everyone the **trade** is ending, please send me your wonderful art using the \&quot;{0}ra\&quot; or \&quot;{1}reveal art\&quot; command..
        /// </summary>
        internal static string GOOGLE_TRADE_ENDING_NOW {
            get {
                return ResourceManager.GetString("GOOGLE_TRADE_ENDING_NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @everyone the art **Trade month** will be ending in {0} days, please reveal your art submissions until then..
        /// </summary>
        internal static string GOOGLE_TRADE_ENDING_SOON {
            get {
                return ResourceManager.GetString("GOOGLE_TRADE_ENDING_SOON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am art-trade-bot, written in Discord.Net ({0}).
        ///For more information about a specific command please type {1}{2} followed by the command name at the end.
        ///For example `{1}{2} {3}`.
        /// </summary>
        internal static string INFO_INTRO {
            get {
                return ResourceManager.GetString("INFO_INTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello &lt;@{0}&gt;! Your hidden art trade partner was **{1}** and they are ready to show you their work for the {2} themed art trade!!.
        /// </summary>
        internal static string REF_REVEAL_FINAL {
            get {
                return ResourceManager.GetString("REF_REVEAL_FINAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for the reveal &lt;@{0}&gt; A notification was sent to your partner &lt;@{1}&gt;..
        /// </summary>
        internal static string REF_REVEAL_NOTIFY {
            get {
                return ResourceManager.GetString("REF_REVEAL_NOTIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry &lt;@{0}&gt; but you did not commit the art for the last trade {1}, you cannot enter the current trade.
        ///(you can use `{2}{3}` command to register the missing trade).
        /// </summary>
        internal static string REF_TRADE_LAST_MONTH_ART_MISSING {
            get {
                return ResourceManager.GetString("REF_TRADE_LAST_MONTH_ART_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your art trade partner is.. {1}, have fun &lt;@{0}&gt;!.
        /// </summary>
        internal static string REF_TRADE_PARTNER {
            get {
                return ResourceManager.GetString("REF_TRADE_PARTNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hello &lt;@{0}&gt; {1}
        ///(if you don&apos;t want to see messages like this, you can use the {2}{3} command to unsubscribe).
        /// </summary>
        internal static string SUBSCRIBERS_NOTICE {
            get {
                return ResourceManager.GetString("SUBSCRIBERS_NOTICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello &lt;@{0}&gt;the current trade ({1} themed) is ending but you did not reveal your art in time, please do so as soon as you have the time, thanks!.
        /// </summary>
        internal static string TRADE_ART_LATE_DM {
            get {
                return ResourceManager.GetString("TRADE_ART_LATE_DM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The art trade ends on.. {0}..
        /// </summary>
        internal static string TRADE_ENDS_ON {
            get {
                return ResourceManager.GetString("TRADE_ENDS_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `{0}` is currently active.
        /// </summary>
        internal static string TRADE_LIST_ONOFF {
            get {
                return ResourceManager.GetString("TRADE_LIST_ONOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing other info.. working channel is.. \&quot;{0}\&quot;, trade is taking place from.. {1} to {2} ({3} days), notify flags.. {4}, trade end forced.. {5}.
        /// </summary>
        internal static string TRADE_LIST_SETTINGS {
            get {
                return ResourceManager.GetString("TRADE_LIST_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @everyone the art **trade month** started. **We are no longer accepting new entries!**
        ///please use `{0}{1}` to show your finished art piece at the `end` of the month or use `{0}{2}` if you need more info
        ///but please wait until the end of the trade when everybody has fihisned their art too.
        /// </summary>
        internal static string TRADE_MONTH {
            get {
                return ResourceManager.GetString("TRADE_MONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hello &lt;@{0}&gt; I&apos;m sending you a message from `{1}` in their stead
        ///please use the `{2}{3}` command if you wish to reply, here is the message:
        ///*\&quot;{4}\&quot;*.
        /// </summary>
        internal static string TRADE_PINGPONG {
            get {
                return ResourceManager.GetString("TRADE_PINGPONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you can use the `{2}{3}` command to register the missing art.
        /// </summary>
        internal static string TRADE_REGISTER_MISSING_ART {
            get {
                return ResourceManager.GetString("TRADE_REGISTER_MISSING_ART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @everyone please choose which theme you&apos;d like for this month&apos;s art trade 
        ///theme with the most votes wins! (^•^).
        /// </summary>
        internal static string TRADE_THEME_POOL_START {
            get {
                return ResourceManager.GetString("TRADE_THEME_POOL_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `{0}` is currently taking place in `{1}` channel (^•^).
        /// </summary>
        internal static string TRADE_THEME_POOL_SUBS {
            get {
                return ResourceManager.GetString("TRADE_THEME_POOL_SUBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme of this month&apos;s art trade is.. \&quot;{0}\&quot;..
        /// </summary>
        internal static string TRADE_THIS_THEME {
            get {
                return ResourceManager.GetString("TRADE_THIS_THEME", resourceCulture);
            }
        }
    }
}
